apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  labels:
    app: operator
spec:
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
      - name: proxycontainer
        image: lachlanevenson/k8s-kubectl
        imagePullPolicy: Always
        command: ["kubectl","proxy","--port=8001"]
      - name: app
        image: mariogrdn/go-operator
        env:
          - name: NET_CARD
            value: network_card_name
          - name: res_namespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
